#!/bin/bash

echo "========================================="
echo "Ngrok Setup for ARRS"
echo "========================================="
echo ""
echo "Step 1: Sign up for free ngrok account"
echo "Visit: https://dashboard.ngrok.com/signup"
echo ""
echo "Step 2: Get your authtoken"
echo "Visit: https://dashboard.ngrok.com/get-started/your-authtoken"
echo ""
echo "Step 3: Run this command with your token:"
echo "ngrok config add-authtoken YOUR_TOKEN_HERE"
echo ""
echo "Step 4: Start ARRS with custom domain:"
echo "./start_with_ngrok.sh"
echo ""
echo "========================================="
